#!/bin/bash
set -euo pipefail

# Set any environment variables here
# These are inherited by all processes, *except* RStudio

# Tell applications where to open desktop apps - this allows notebooks to
# pop open GUIs
export DISPLAY=":1.0"


exec "$@"
