name: build jupyterhub image
on:
  workflow_run:
    workflows: [update conda lockfile]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - .github/workflows/repo2docker.yaml
      - conda-lock.yml
      - apt.txt
      - environment.yml
      - start
      - appendix
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    # For biggish images, github actions runs out of disk space.
    # So we cleanup some unwanted things in the disk image, and reclaim that space for our docker use
    # https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
    # and https://github.com/easimon/maximize-build-space/blob/b4d02c14493a9653fe7af06cc89ca5298071c66e/action.yml#L104
    # This gives us a total of about 52G of free space, which should be enough for now
    - name: cleanup disk space
      run: |
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h
        
    - name: checkout files in repo
      uses: actions/checkout@main
      
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{github.actor}}
        DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        DOCKER_REGISTRY: ghcr.io
        IMAGE_NAME: nmfs-opensci/base-hub-image
        APPENDIX_FILE: appendix

    # Lets us monitor disks getting full as images get bigger over time
    - name: Show how much disk space is left
      run: df -h
